# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from private.pb import nodeapi_pb2 as private_dot_pb_dot_nodeapi__pb2


class NodeAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BucketCreate = channel.unary_unary(
                '/nodeapi.NodeAPI/BucketCreate',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.BucketCreateRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.BucketCreateResponse.FromString,
                )
        self.BucketView = channel.unary_unary(
                '/nodeapi.NodeAPI/BucketView',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.BucketViewRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.BucketViewResponse.FromString,
                )
        self.BucketList = channel.unary_unary(
                '/nodeapi.NodeAPI/BucketList',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.BucketListRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.BucketListResponse.FromString,
                )
        self.BucketDelete = channel.unary_unary(
                '/nodeapi.NodeAPI/BucketDelete',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.BucketDeleteRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.BucketDeleteResponse.FromString,
                )


class NodeAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BucketCreate(self, request, context):
        """Bucket APIs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BucketCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketCreate,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.BucketCreateRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.BucketCreateResponse.SerializeToString,
            ),
            'BucketView': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketView,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.BucketViewRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.BucketViewResponse.SerializeToString,
            ),
            'BucketList': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketList,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.BucketListRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.BucketListResponse.SerializeToString,
            ),
            'BucketDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketDelete,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.BucketDeleteRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.BucketDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeapi.NodeAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BucketCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.NodeAPI/BucketCreate',
            private_dot_pb_dot_nodeapi__pb2.BucketCreateRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.BucketCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BucketView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.NodeAPI/BucketView',
            private_dot_pb_dot_nodeapi__pb2.BucketViewRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.BucketViewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BucketList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.NodeAPI/BucketList',
            private_dot_pb_dot_nodeapi__pb2.BucketListRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.BucketListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BucketDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.NodeAPI/BucketDelete',
            private_dot_pb_dot_nodeapi__pb2.BucketDeleteRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.BucketDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class StreamAPIStub(object):
    """Stream APIs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileUploadCreate = channel.unary_unary(
                '/nodeapi.StreamAPI/FileUploadCreate',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCreateRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCreateResponse.FromString,
                )
        self.FileUploadChunkCreate = channel.unary_unary(
                '/nodeapi.StreamAPI/FileUploadChunkCreate',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadChunkCreateRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadChunkCreateResponse.FromString,
                )
        self.FileUploadBlock = channel.stream_unary(
                '/nodeapi.StreamAPI/FileUploadBlock',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileBlockData.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadBlockResponse.FromString,
                )
        self.FileUploadCommit = channel.unary_unary(
                '/nodeapi.StreamAPI/FileUploadCommit',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCommitRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCommitResponse.FromString,
                )
        self.FileDownloadCreate = channel.unary_unary(
                '/nodeapi.StreamAPI/FileDownloadCreate',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadCreateRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadCreateResponse.FromString,
                )
        self.FileDownloadRangeCreate = channel.unary_unary(
                '/nodeapi.StreamAPI/FileDownloadRangeCreate',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadRangeCreateRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadCreateResponse.FromString,
                )
        self.FileDownloadChunkCreate = channel.unary_unary(
                '/nodeapi.StreamAPI/FileDownloadChunkCreate',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateResponse.FromString,
                )
        self.FileDownloadChunkCreateV2 = channel.unary_unary(
                '/nodeapi.StreamAPI/FileDownloadChunkCreateV2',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateResponseV2.FromString,
                )
        self.FileDownloadBlock = channel.unary_stream(
                '/nodeapi.StreamAPI/FileDownloadBlock',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadBlockRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileBlockData.FromString,
                )
        self.FileList = channel.unary_unary(
                '/nodeapi.StreamAPI/FileList',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileListRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileListResponse.FromString,
                )
        self.FileView = channel.unary_unary(
                '/nodeapi.StreamAPI/FileView',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileViewRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileViewResponse.FromString,
                )
        self.FileVersions = channel.unary_unary(
                '/nodeapi.StreamAPI/FileVersions',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileListVersionsRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileListVersionsResponse.FromString,
                )
        self.FileDelete = channel.unary_unary(
                '/nodeapi.StreamAPI/FileDelete',
                request_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDeleteRequest.SerializeToString,
                response_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDeleteResponse.FromString,
                )


class StreamAPIServicer(object):
    """Stream APIs.
    """

    def FileUploadCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileUploadChunkCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileUploadBlock(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileUploadCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDownloadCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDownloadRangeCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDownloadChunkCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDownloadChunkCreateV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDownloadBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FileUploadCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.FileUploadCreate,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCreateRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCreateResponse.SerializeToString,
            ),
            'FileUploadChunkCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.FileUploadChunkCreate,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadChunkCreateRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadChunkCreateResponse.SerializeToString,
            ),
            'FileUploadBlock': grpc.stream_unary_rpc_method_handler(
                    servicer.FileUploadBlock,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileBlockData.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadBlockResponse.SerializeToString,
            ),
            'FileUploadCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.FileUploadCommit,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCommitRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCommitResponse.SerializeToString,
            ),
            'FileDownloadCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.FileDownloadCreate,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadCreateRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadCreateResponse.SerializeToString,
            ),
            'FileDownloadRangeCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.FileDownloadRangeCreate,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadRangeCreateRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadCreateResponse.SerializeToString,
            ),
            'FileDownloadChunkCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.FileDownloadChunkCreate,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateResponse.SerializeToString,
            ),
            'FileDownloadChunkCreateV2': grpc.unary_unary_rpc_method_handler(
                    servicer.FileDownloadChunkCreateV2,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateResponseV2.SerializeToString,
            ),
            'FileDownloadBlock': grpc.unary_stream_rpc_method_handler(
                    servicer.FileDownloadBlock,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadBlockRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileBlockData.SerializeToString,
            ),
            'FileList': grpc.unary_unary_rpc_method_handler(
                    servicer.FileList,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileListRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileListResponse.SerializeToString,
            ),
            'FileView': grpc.unary_unary_rpc_method_handler(
                    servicer.FileView,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileViewRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileViewResponse.SerializeToString,
            ),
            'FileVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.FileVersions,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileListVersionsRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileListVersionsResponse.SerializeToString,
            ),
            'FileDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.FileDelete,
                    request_deserializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDeleteRequest.FromString,
                    response_serializer=private_dot_pb_dot_nodeapi__pb2.StreamFileDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nodeapi.StreamAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamAPI(object):
    """Stream APIs.
    """

    @staticmethod
    def FileUploadCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileUploadCreate',
            private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCreateRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileUploadChunkCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileUploadChunkCreate',
            private_dot_pb_dot_nodeapi__pb2.StreamFileUploadChunkCreateRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileUploadChunkCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileUploadBlock(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/nodeapi.StreamAPI/FileUploadBlock',
            private_dot_pb_dot_nodeapi__pb2.StreamFileBlockData.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileUploadBlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileUploadCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileUploadCommit',
            private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCommitRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileUploadCommitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileDownloadCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileDownloadCreate',
            private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadCreateRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileDownloadRangeCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileDownloadRangeCreate',
            private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadRangeCreateRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileDownloadChunkCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileDownloadChunkCreate',
            private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileDownloadChunkCreateV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileDownloadChunkCreateV2',
            private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadChunkCreateResponseV2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileDownloadBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/nodeapi.StreamAPI/FileDownloadBlock',
            private_dot_pb_dot_nodeapi__pb2.StreamFileDownloadBlockRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileBlockData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileList',
            private_dot_pb_dot_nodeapi__pb2.StreamFileListRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileView',
            private_dot_pb_dot_nodeapi__pb2.StreamFileViewRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileViewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileVersions',
            private_dot_pb_dot_nodeapi__pb2.StreamFileListVersionsRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileListVersionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nodeapi.StreamAPI/FileDelete',
            private_dot_pb_dot_nodeapi__pb2.StreamFileDeleteRequest.SerializeToString,
            private_dot_pb_dot_nodeapi__pb2.StreamFileDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
